name: 'Build'

on:
# 定时触发
#  schedule:
#    - cron: 0 20 * * *

# 点赞触发
  watch:
    types: [started]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          npm run build
