name: Release

on:
# 定时触发
#  schedule:
#    - cron: 0 20 * * *

# 点赞触发
  watch:
    types: [started]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/boilerplate-card/boilerplate-card
          npm install
          npm run build

      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/boilerplate-card/boilerplate-card/dist/boilerplate-card.js
          asset_name: boilerplate-card.js
          tag: ${{ github.ref }}
          overwrite: true
